# Tablero Como vamos
## Vicepresidencia de Planeación - Turismo

In [509]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import matplotlib as mpl 
import six
import os 

pathout = './data/'
if not os.path.exists(pathout):
    os.mkdir(pathout) 
    pathgraphs = './graphs/'
    if not os.path.exists(pathgraphs): 
        os.mkdir(pathgraphs)

In [510]:
Metas = pd.read_excel(pathout + 'MetasMayo.xlsx')

In [511]:
Negocios = pd.read_excel(pathout + 'NegociosMayo.xlsx')

In [512]:
Oportunidades = pd.read_excel(pathout + 'OportunidadesMayo.xlsx')

In [513]:
ENacionales = pd.read_excel(pathout + 'EmpresasMayo.xlsx')

In [514]:
#Frecuencias = pd.read_excel(pathout + 'Frecuencias.xlsx')

In [515]:
ProyectoseHitos = pd.read_excel(pathout + 'PeHMayo.xlsx')

E:\Usuario\pplaneacion\Anaconda3\lib\site-packages\openpyxl\styles\stylesheet.py:226: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [516]:
#ProyectoseHitos = pd.read_csv(pathout + 'ProyectoseHitos.csv' , delimiter = ';' ,  encoding = 'iso-8859-1')

In [517]:
AsistentesPFE1 =  pd.read_excel(pathout + 'PFE15may.xlsx')

In [518]:
AsistentesPFE2020 =  pd.read_excel(pathout + 'PFE2021.xlsx')

In [519]:
#SillasyFrecuencias2020 =  pd.read_excel(pathout + 'SillasyFrecuencias2020.xlsx')

In [520]:
añoactual = 2022
añoanterior = 2021
trimestre = 2

#Fecha en Formato aaaa/mm/dd para la base de Tableau 12a
negociosañoactual = '2022-01-01'
fechaactual  = '2022-06-01'
fechaactual2  = '1/01/2022'
fechaanterior2 = '1/01/2021'
eneroañoanterior = '2021-01-01'
fechaactual_añoanterior = '2021-06-01'
diciembreañoanterior = '2021-12-31'


#Valores
frecuencias = 1160
nsillas = 199579
nVisitantes =  914882
mVisitantes = 3100000
mqVisitantes = 89900
mVisitanterior = 2157504

In [521]:
ProyectoseHitos['Hito: Fecha Inicio'].replace('', np.nan, inplace=True)
ProyectoseHitos.dropna(subset=['Hito: Fecha Inicio'], inplace=True)

In [522]:
MetasT =  Metas.drop(Metas[Metas['Meta: Eje'] != 'Turismo'].index)
MetasT = MetasT.drop(MetasT[MetasT['Meta: Año'] !=  añoactual].index)
MetasTQ = MetasT.drop(MetasT[MetasT['Meta: Período'] > trimestre].index)

MetasT_Anterior =  Metas.drop(Metas[Metas['Meta: Eje'] != 'Turismo'].index)
MetasT_Anterior = MetasT_Anterior.drop(MetasT_Anterior[MetasT_Anterior['Meta: Año'] !=  añoanterior].index)
MetasTQ_Anterior = MetasT_Anterior.drop(MetasT_Anterior[MetasT_Anterior['Meta: Período'] > trimestre].index)

In [523]:
NegociosT = Negocios.drop(Negocios[Negocios['Logro: Eje'] != 'Turismo'].index)
NegociosT = NegociosT.drop(NegociosT[NegociosT['Meta 1 responsable Colombia: Año'] !=  añoactual].index)

NegociosTA = Negocios.drop(Negocios[Negocios['Logro: Eje'] != 'Turismo'].index)
NegociosTA = NegociosTA.drop(NegociosTA[NegociosTA['Meta 1 responsable Colombia: Año'] !=  añoanterior].index)

### Metas y Metas Q

#### 2021

In [524]:
MetasT = MetasT.groupby(['Meta: Tipo meta funcionario'  , 
                   'E_Localización' , 'E_Clasificación' , 
                   'Meta: Nombre del propietario' , 'E_Rol',
                  'Tipo de Indicador' , 'Meta: Tipo de meta'])['Meta: Valor meta'].sum().reset_index()

MetasTQ = MetasTQ.groupby(['Meta: Tipo meta funcionario', 
                   'E_Localización' , 'E_Clasificación' , 
                   'Meta: Nombre del propietario' , 'E_Rol',
                  'Tipo de Indicador' , 'Meta: Tipo de meta'])['Meta: Valor meta'].sum().reset_index()

In [525]:

TFinal = MetasT.merge(MetasTQ, how='outer', left_on=['Meta: Tipo meta funcionario' , 
                   'E_Localización' , 'E_Clasificación' , 
                   'Meta: Nombre del propietario' , 'E_Rol',
                  'Tipo de Indicador' , 'Meta: Tipo de meta'], right_on=['Meta: Tipo meta funcionario' , 
                   'E_Localización' , 'E_Clasificación' , 
                   'Meta: Nombre del propietario' , 'E_Rol',
                  'Tipo de Indicador' , 'Meta: Tipo de meta']).fillna(0)

TFinal.rename(columns={'Meta: Valor meta_x': 'Meta Total' , 'Meta: Valor meta_y': 'Meta Q'}, inplace=True)

In [526]:

#mask = ((TFinal['Meta: Tipo de meta'] == 'Captación de Congresos y Eventos') | 
 #       (TFinal['Meta: Tipo meta funcionario'] == 'COLOMBIA'))
#TFinal.loc[mask, 'E_HUB2019'] = 'COLOMBIA'

TFinal

,Meta: Tipo meta funcionario,E_Localización,E_Clasificación,Meta: Nombre del propietario,E_Rol,Tipo de Indicador,Meta: Tipo de meta,Meta Total,Meta Q
0,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Comercial,Captación de Congresos y Eventos,11.0,7.0
1,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Comercial,Monto de gasto de noches,1800000.0,700000.0
2,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Comercial,Monto de gasto paquetes,517850.0,140000.0
3,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Gestión,Número asistentes PFE turismo,1040.0,540.0
4,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Gestión,Número de empresas con servicios en turismo,80.0,25.0
...,...,...,...,...,...,...,...,...,...
153,EXTERIOR,Reino Unido,Oficom,Juliana Torres Nieto,Asesor Oficom,Gestión,Número de empresas con servicios en turismo,100.0,40.0
154,EXTERIOR,Turquía,Oficom,Marcela Monroy Hernandez (VACANTE),Director Oficom,Comercial,Captación de Congresos y Eventos,2.0,1.0
155,EXTERIOR,Turquía,Oficom,Marcela Monroy Hernandez (VACANTE),Director Oficom,Gestión,Número de empresas con servicios en turismo,45.0,25.0
156,EXTERIOR,Venezuela,Oficom,Humberto Rodriguez,Asesor Oficom,Comercial,Captación de Congresos y Eventos,1.0,0.0
157,EXTERIOR,Venezuela,Oficom,Humberto Rodriguez,Asesor Oficom,Gestión,Número de empresas con servicios en turismo,115.0,55.0

### Captación de Congresos y Eventos

#### 2021

In [527]:

Negocios_Captacion_2021 = NegociosT.drop(NegociosT[NegociosT['Logro: Tipo de registro'] !=  'Captación de Eventos'].index)

Negocios_Captacion_Col_2021 = Negocios_Captacion_2021.groupby(['Logro: Responsable Colombia' , 'Logro: Tipo de registro' 
                                                          ])['Logro: Valor'].sum().reset_index()

Negocios_Captacion_Ext_2021 = Negocios_Captacion_2021.groupby(['Logro: Responsable en el Exterior 1' , 'Logro: Tipo de registro' 
                                                          ])['Logro: Valor'].sum().reset_index()


Negocios_Captacion_Col_2021.rename(columns={'Logro: Responsable Colombia': 'Meta: Nombre del propietario'}, inplace=True)
Negocios_Captacion_Ext_2021.rename(columns={'Logro: Responsable en el Exterior 1': 'Meta: Nombre del propietario'}, inplace=True)

Negocios_Captacion_2021 = Negocios_Captacion_Col_2021.append(Negocios_Captacion_Ext_2021)
Negocios_Captacion_2021.rename(columns={'Logro: Tipo de registro': 'Meta: Tipo de meta'}, inplace=True)


#Falta captacion de Congresos

Negocios_CaptacionCyE_2021 = Negocios_Captacion_2021

Negocios_CaptacionCyE_2021 = (Negocios_CaptacionCyE_2021.replace('Captación de Eventos', 'Captación de Congresos y Eventos'))

In [528]:
Negocios_CaptacionCyE_2021

,Meta: Nombre del propietario,Meta: Tipo de meta,Logro: Valor
0,Carlos Mario Gonzalez Velasquez,Captación de Congresos y Eventos,1.0
1,Daniela Mesa (Vacante),Captación de Congresos y Eventos,8.0
2,Daniela Rodriguez Lemaitre,Captación de Congresos y Eventos,3.0
3,Eduardo Andres Sanchez,Captación de Congresos y Eventos,2.0
4,Jose Fernando Villaquiran Fernandez,Captación de Congresos y Eventos,2.0
5,Katherin Paola Carrillo Gonzalez (vacante),Captación de Congresos y Eventos,5.0
6,Kimberly Escobar,Captación de Congresos y Eventos,7.0
7,Luisa Fernanda Cuellar Sarmiento,Captación de Congresos y Eventos,3.0
8,María Francisca Símaro,Captación de Congresos y Eventos,28.0
9,Mauricio Tellez Abueita,Captación de Congresos y Eventos,3.0
10,Silvia Juliana Díaz Reyes,Captación de Congresos y Eventos,4.0
11,Vanessa Botero Botero,Captación de Congresos y Eventos,6.0
0,Ana Catalina Hernandez Florez,Captación de Congresos y Eventos,5.0
1,Ana Maria Rojas Perea,Captación de Congresos y Eventos,1.0
2,Andrea Daza Aldana,Captación de Congresos y Eventos,5.0
3,Andres Calle,Captación de Congresos y Eventos,1.0
4,Constanza Durán Bahamón,Captación de Congresos y Eventos,4.0
5,Cristian Alberto Duque Giraldo,Captación de Congresos y Eventos,1.0
6,Dayana Maria Martinez Granados,Captación de Congresos y Eventos,1.0
7,Director Oficom Otros,Captación de Congresos y Eventos,7.0
8,Humberto Rodriguez,Captación de Congresos y Eventos,2.0
9,Lina María Patarroyo Castillo,Captación de Congresos y Eventos,3.0
10,Marcela Villa,Captación de Congresos y Eventos,1.0
11,Maria Carolina Rico Gonzalez,Captación de Congresos y Eventos,1.0
12,Mariana Awad Zaher,Captación de Congresos y Eventos,32.0
13,Oscar Javier Martinez Puentes,Captación de Congresos y Eventos,1.0
14,Patricia Salinas,Captación de Congresos y Eventos,2.0
15,Paula Andrea Giraldo Uribe,Captación de Congresos y Eventos,4.0
16,Santiago De los Rios Cardona,Captación de Congresos y Eventos,1.0

In [529]:
TFinal = TFinal.merge(Negocios_CaptacionCyE_2021, how='outer', left_on=['Meta: Nombre del propietario' , 'Meta: Tipo de meta'], 
                      right_on=['Meta: Nombre del propietario' , 'Meta: Tipo de meta']).fillna(0)

In [530]:
TFinal

,Meta: Tipo meta funcionario,E_Localización,E_Clasificación,Meta: Nombre del propietario,E_Rol,Tipo de Indicador,Meta: Tipo de meta,Meta Total,Meta Q,Logro: Valor
0,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Comercial,Captación de Congresos y Eventos,11.0,7.0,6.0
1,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Comercial,Monto de gasto de noches,1800000.0,700000.0,0.0
2,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Comercial,Monto de gasto paquetes,517850.0,140000.0,0.0
3,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Gestión,Número asistentes PFE turismo,1040.0,540.0,0.0
4,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Gestión,Número de empresas con servicios en turismo,80.0,25.0,0.0
...,...,...,...,...,...,...,...,...,...,...
153,EXTERIOR,Reino Unido,Oficom,Juliana Torres Nieto,Asesor Oficom,Gestión,Número de empresas con servicios en turismo,100.0,40.0,0.0
154,EXTERIOR,Turquía,Oficom,Marcela Monroy Hernandez (VACANTE),Director Oficom,Comercial,Captación de Congresos y Eventos,2.0,1.0,0.0
155,EXTERIOR,Turquía,Oficom,Marcela Monroy Hernandez (VACANTE),Director Oficom,Gestión,Número de empresas con servicios en turismo,45.0,25.0,0.0
156,EXTERIOR,Venezuela,Oficom,Humberto Rodriguez,Asesor Oficom,Comercial,Captación de Congresos y Eventos,1.0,0.0,2.0
157,EXTERIOR,Venezuela,Oficom,Humberto Rodriguez,Asesor Oficom,Gestión,Número de empresas con servicios en turismo,115.0,55.0,0.0

#### 2020

In [531]:
Negocios_Captacion_2020 = NegociosTA.drop(NegociosTA[NegociosTA['Logro: Tipo de registro'] !=  'Captación de Eventos'].index)

Negocios_Captacion_Col_2020 = Negocios_Captacion_2020.groupby(['Logro: Responsable Colombia' , 'Logro: Tipo de registro' 
                                                          ])['Logro: Valor'].sum().reset_index()

Negocios_Captacion_Ext_2020 = Negocios_Captacion_2020.groupby(['Logro: Responsable en el Exterior 1' , 'Logro: Tipo de registro' 
                                                          ])['Logro: Valor'].sum().reset_index()


Negocios_Captacion_Col_2020.rename(columns={'Logro: Responsable Colombia': 'Meta: Nombre del propietario'}, inplace=True)
Negocios_Captacion_Ext_2020.rename(columns={'Logro: Responsable en el Exterior 1': 'Meta: Nombre del propietario'}, inplace=True)

Negocios_Captacion_2020 = Negocios_Captacion_Col_2020.append(Negocios_Captacion_Ext_2020)
Negocios_Captacion_2020.rename(columns={'Logro: Tipo de registro': 'Meta: Tipo de meta'}, inplace=True)

#Falta captacion de Congresos

Negocios_CaptacionCyE_2020 = Negocios_Captacion_2020

Negocios_CaptacionCyE_2020 = (Negocios_CaptacionCyE_2020.replace('Captación de Eventos', 'Captación de Congresos y Eventos'))
Negocios_CaptacionCyE_2020.rename(columns={'Logro: Valor': 'Valor 2020'}, inplace=True)

In [532]:
TFinal = TFinal.merge(Negocios_CaptacionCyE_2020, how='outer', left_on=['Meta: Nombre del propietario' , 'Meta: Tipo de meta'], 
                      right_on=['Meta: Nombre del propietario' , 'Meta: Tipo de meta']).fillna(0)

In [533]:
TFinal

,Meta: Tipo meta funcionario,E_Localización,E_Clasificación,Meta: Nombre del propietario,E_Rol,Tipo de Indicador,Meta: Tipo de meta,Meta Total,Meta Q,Logro: Valor,Valor 2020
0,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Comercial,Captación de Congresos y Eventos,11.0,7.0,6.0,8.0
1,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Comercial,Monto de gasto de noches,1800000.0,700000.0,0.0,0.0
2,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Comercial,Monto de gasto paquetes,517850.0,140000.0,0.0,0.0
3,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Gestión,Número asistentes PFE turismo,1040.0,540.0,0.0,0.0
4,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Gestión,Número de empresas con servicios en turismo,80.0,25.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
156,EXTERIOR,Venezuela,Oficom,Humberto Rodriguez,Asesor Oficom,Comercial,Captación de Congresos y Eventos,1.0,0.0,2.0,0.0
157,EXTERIOR,Venezuela,Oficom,Humberto Rodriguez,Asesor Oficom,Gestión,Número de empresas con servicios en turismo,115.0,55.0,0.0,0.0
158,0,0,0,Maria Eugenia Oriani Ucros,0,0,Captación de Congresos y Eventos,0.0,0.0,0.0,3.0
159,0,0,0,Andres Felipe Gonzalez Gutierrez (VACANTE),0,0,Captación de Congresos y Eventos,0.0,0.0,0.0,1.0
160,0,0,0,Nicolas Casasfranco Jimenez,0,0,Captación de Congresos y Eventos,0.0,0.0,0.0,1.0

### Oportunidades en Etapa 0 y 1

#### 2021

In [534]:
OportT = Oportunidades.drop(Oportunidades[Oportunidades['E_Año'] != añoactual].index)
OportT = OportT.drop(OportT[OportT['Oportunidad: Tipo de registro'] != 'Conectividad aérea'].index)
OportT_0y1 = OportT.drop(OportT[OportT['Oportunidad: Etapa'] == 5].index)
OportT_0y1 = OportT_0y1.drop(OportT_0y1[OportT_0y1['Oportunidad: Etapa'] == 2].index)
OportT_0y1 = OportT_0y1.drop(OportT_0y1[OportT_0y1['Oportunidad: Etapa'] == 3].index)
OportT_0y1 = OportT_0y1.drop(OportT_0y1[OportT_0y1['Oportunidad: Etapa'] == 4].index)
OportT_0y1Nacio = OportT_0y1.groupby(['Oportunidad: Responsable en Colombia'])['Oportunidad: Consecutivo'].count().reset_index()
OportT_0y1Ext = OportT_0y1.groupby(['Oportunidad: Responsable en el exterior 1'])['Oportunidad: Consecutivo'].count().reset_index()


OportT_0y1Nacio.rename(columns={'Oportunidad: Consecutivo': 'Logro: Valor' , 
                       'Oportunidad: Responsable en Colombia': 'Meta: Nombre del propietario'}, inplace=True)
OportT_0y1Ext.rename(columns={'Oportunidad: Consecutivo': 'Logro: Valor' , 
                       'Oportunidad: Responsable en el exterior 1': 'Meta: Nombre del propietario'}, inplace=True)
OportT_0y1 = OportT_0y1Nacio.append(OportT_0y1Ext, ignore_index=True)

OportT_0y1['Meta: Tipo de meta'] = 'Número de oportunidades en etapa 0 y 1'

OportT_0y11 =OportT_0y1.groupby(['Meta: Tipo de meta'])['Logro: Valor'].sum().reset_index()
OportT_0y11['Logro: Valor'] = OportT_0y11['Logro: Valor']*0.5

In [535]:
TFinal = TFinal.merge(OportT_0y11, how='left', left_on=['Meta: Tipo de meta'], 
                      right_on=['Meta: Tipo de meta']).fillna(0)

In [536]:
TFinal['Valor'] = TFinal['Logro: Valor_x'] + TFinal['Logro: Valor_y']
TFinal = TFinal.drop(columns=['Logro: Valor_x', 'Logro: Valor_y'])

### Oportunidades en Etapa 2 y 3

#### 2021

In [537]:
OportT = Oportunidades.drop(Oportunidades[Oportunidades['E_Año'] != añoactual].index)
OportT = OportT.drop(OportT[OportT['Oportunidad: Tipo de registro'] != 'Conectividad aérea'].index)
OportT_2y3 = OportT.drop(OportT[OportT['Oportunidad: Etapa'] == 5].index)
OportT_2y3 = OportT_2y3.drop(OportT_2y3[OportT_2y3['Oportunidad: Etapa'] == 0].index)
OportT_2y3 = OportT_2y3.drop(OportT_2y3[OportT_2y3['Oportunidad: Etapa'] == 1].index)
OportT_2y3 = OportT_2y3.drop(OportT_2y3[OportT_2y3['Oportunidad: Etapa'] == 4].index)



OportT_2y3Nacio = OportT_2y3.groupby(['Oportunidad: Responsable en Colombia'])['Oportunidad: Consecutivo'].count().reset_index()
OportT_2y3Ext = OportT_2y3.groupby(['Oportunidad: Responsable en el exterior 1'])['Oportunidad: Consecutivo'].count().reset_index()


OportT_2y3Nacio.rename(columns={'Oportunidad: Consecutivo': 'Logro: Valor' , 
                       'Oportunidad: Responsable en Colombia': 'Meta: Nombre del propietario'}, inplace=True)
OportT_2y3Ext.rename(columns={'Oportunidad: Consecutivo': 'Logro: Valor' , 
                       'Oportunidad: Responsable en el exterior 1': 'Meta: Nombre del propietario'}, inplace=True)
OportT_2y3 = OportT_2y3Nacio.append(OportT_2y3Ext, ignore_index=True)

OportT_2y3['Meta: Tipo de meta'] = 'Número de oportunidades en etapa 2 y 3'

In [538]:
#OportT_2y3 = OportT_2y3.groupby(['Meta: Tipo de meta'])['Logro: Valor'].sum().reset_index()
OportT_2y32 =OportT_2y3.groupby(['Meta: Tipo de meta'])['Logro: Valor'].sum().reset_index()
OportT_2y32['Logro: Valor'] = OportT_2y32['Logro: Valor']*0.5

In [539]:
TFinal = TFinal.merge(OportT_2y32, how='left', left_on=['Meta: Tipo de meta'], 
                      right_on=['Meta: Tipo de meta']).fillna(0)

In [540]:

TFinal['Valor'] = TFinal['Valor'] + TFinal['Logro: Valor']
TFinal = TFinal.drop(columns=['Logro: Valor'])

### Monto de Gasto de Noches

#### 2021

In [541]:
MontoGastoNoches = NegociosT.drop(NegociosT[NegociosT['Logro: Tipo de registro'] !=  'Turismo Noches'].index)

MontoGastoNoches = MontoGastoNoches.groupby(['Logro: Responsable Colombia' , 'Logro: Tipo de registro' 
                                                          ])['Logro: Valor'].sum().reset_index()

MontoGastoNoches.rename(columns={'Logro: Responsable Colombia': 'Meta: Nombre del propietario'}, inplace=True)
MontoGastoNoches.rename(columns={'Logro: Tipo de registro': 'Meta: Tipo de meta'}, inplace=True)


MontoGastoNoches = (MontoGastoNoches.replace('Turismo Noches', 'Monto de gasto de noches'))

In [542]:
TFinal = TFinal.merge(MontoGastoNoches, how='outer', left_on=['Meta: Nombre del propietario' , 'Meta: Tipo de meta'], 
                      right_on=['Meta: Nombre del propietario' , 'Meta: Tipo de meta']).fillna(0)


TFinal['Valor'] = TFinal['Valor'] + TFinal['Logro: Valor']
TFinal = TFinal.drop(columns=['Logro: Valor'])

#### 2020

In [543]:
MontoGastoNochesA = NegociosTA.drop(NegociosTA[NegociosTA['Logro: Tipo de registro'] !=  'Turismo Noches'].index)

MontoGastoNochesA = MontoGastoNochesA.groupby(['Logro: Responsable Colombia' , 'Logro: Tipo de registro' 
                                                          ])['Logro: Valor'].sum().reset_index()

MontoGastoNochesA.rename(columns={'Logro: Responsable Colombia': 'Meta: Nombre del propietario'}, inplace=True)
MontoGastoNochesA.rename(columns={'Logro: Tipo de registro': 'Meta: Tipo de meta'}, inplace=True)


MontoGastoNochesA = (MontoGastoNochesA.replace('Turismo Noches', 'Monto de gasto de noches'))

In [544]:
TFinal = TFinal.merge(MontoGastoNochesA, how='outer', left_on=['Meta: Nombre del propietario' , 'Meta: Tipo de meta'], 
                      right_on=['Meta: Nombre del propietario' , 'Meta: Tipo de meta']).fillna(0)


TFinal['Valor 2020'] = TFinal['Valor 2020'] + TFinal['Logro: Valor']
TFinal = TFinal.drop(columns=['Logro: Valor'])

### Monto de Gasto de Paquetes

#### 2021

In [545]:
MontoPaquetes = NegociosT.drop(NegociosT[NegociosT['Logro: Tipo de registro'] !=  'Paquetes Turismo'].index)

MontoPaquetes = MontoPaquetes.groupby(['Logro: Responsable Colombia' , 'Logro: Tipo de registro' 
                                                          ])['Logro: Valor'].sum().reset_index()

MontoPaquetes.rename(columns={'Logro: Responsable Colombia': 'Meta: Nombre del propietario'}, inplace=True)
MontoPaquetes.rename(columns={'Logro: Tipo de registro': 'Meta: Tipo de meta'}, inplace=True)


MontoPaquetes = (MontoPaquetes.replace('Paquetes Turismo', 'Monto de gasto paquetes'))

In [546]:
TFinal = TFinal.merge(MontoPaquetes, how='outer', left_on=['Meta: Nombre del propietario' , 'Meta: Tipo de meta'], 
                      right_on=['Meta: Nombre del propietario' , 'Meta: Tipo de meta']).fillna(0)


TFinal['Valor'] = TFinal['Valor'] + TFinal['Logro: Valor']
TFinal = TFinal.drop(columns=['Logro: Valor'])

#### 2020

In [547]:
MontoPaquetesA = NegociosTA.drop(NegociosTA[NegociosTA['Logro: Tipo de registro'] !=  'Paquetes Turismo'].index)

MontoPaquetesA = MontoPaquetesA.groupby(['Logro: Responsable Colombia' , 'Logro: Tipo de registro' 
                                                          ])['Logro: Valor'].sum().reset_index()

MontoPaquetesA.rename(columns={'Logro: Responsable Colombia': 'Meta: Nombre del propietario'}, inplace=True)
MontoPaquetesA.rename(columns={'Logro: Tipo de registro': 'Meta: Tipo de meta'}, inplace=True)


MontoPaquetesA = (MontoPaquetesA.replace('Paquetes Turismo', 'Monto de gasto paquetes'))

In [548]:
TFinal = TFinal.merge(MontoPaquetesA, how='outer', left_on=['Meta: Nombre del propietario' , 'Meta: Tipo de meta'], 
                      right_on=['Meta: Nombre del propietario' , 'Meta: Tipo de meta']).fillna(0)


TFinal['Valor 2020'] = TFinal['Valor 2020'] + TFinal['Logro: Valor']
TFinal = TFinal.drop(columns=['Logro: Valor'])

### Número de empresas con servicios en turismo

In [549]:
#ENacionales2 = ENacionales.drop(ENacionales[ENacionales['Año de Fecha creación'] != añoactual].index)
ENacionales2 = ENacionales.drop(ENacionales[ENacionales['Eje'] !=  'Turismo'].index)



ENacionales2 = ENacionales2.drop(ENacionales2[(ENacionales2['Estado'] !=  'Realizada') & 
                                     (ENacionales2['Estado'] !=  'Entregado') & 
                                     (ENacionales2['Estado'] !=  'Realizado') & 
                                    (ENacionales2['Estado'] !=  'Entregada') & 
                                    (ENacionales2['Estado'] !=  'Completed') & 
                                     (ENacionales2['Estado'] !=  'Finalizada') & 
                                     (ENacionales2['Estado'] !=  'Finalizado') & 
                                     (ENacionales2['Estado'] !=  'Realizó evaluación del evento') & 
                                     (ENacionales2['Estado'] !=  'Participó')].index)


ENacionales2['Empresa'] = ENacionales2['Empresa'].str.lower()

ENacionales3 = ENacionales2.drop(ENacionales2[ENacionales2['Fecha'] < eneroañoanterior].index)
ENacionales3 = ENacionales3.drop(ENacionales3[ENacionales3['Fecha'] > fechaactual_añoanterior].index)

Enacionales4 = ENacionales2.drop(ENacionales2[ENacionales2['Año de Fecha creación'] != añoanterior].index)

ENacionales2 = ENacionales2.drop(ENacionales2[ENacionales2['Fecha'] < negociosañoactual].index)
ENacionales2 = ENacionales2.drop(ENacionales2[ENacionales2['Fecha'] > fechaactual].index)

ENacionales_Nacional = ENacionales2.drop(ENacionales2[ENacionales2['Tipo empresa'] !=  'Nacional'].index)
ENacionales_Exterior = ENacionales2.drop(ENacionales2[ENacionales2['Tipo empresa'] !=  'Exterior'].index)

ENacionales_NacionalA = ENacionales3.drop(ENacionales3[ENacionales3['Tipo empresa'] !=  'Nacional'].index)
ENacionales_ExteriorA = ENacionales3.drop(ENacionales3[ENacionales3['Tipo empresa'] !=  'Exterior'].index)

In [550]:



ENacionales_NacionalA.loc[ENacionales_NacionalA['Responsable nacional'] == 'Vanessa Botero Botero']

a2a = ENacionales_Exterior.groupby(['Responsable exterior' ,'Empresa', 'Estado', 'Año de Fecha creación'])['Id empresa'].nunique().reset_index()

a2a.loc[a2a['Responsable exterior'] == 'Santiago De los Rios Cardona']

#ENTuris_Nal

,Responsable exterior,Empresa,Estado,Año de Fecha creación,Id empresa
877,Santiago De los Rios Cardona,air century,Finalizado,2022,1
878,Santiago De los Rios Cardona,arajet,Finalizado,2022,1
879,Santiago De los Rios Cardona,arbaje tours,Finalizada,2022,1
880,Santiago De los Rios Cardona,avianca rd,Finalizada,2022,1

#### 2021

In [551]:
ENTuris_Nal = ENacionales_Nacional.groupby(['Responsable nacional' ])['Id empresa'].nunique().reset_index()
ENTuris_Ext = ENacionales_Exterior.groupby(['Responsable exterior' ])['Id empresa'].nunique().reset_index()

ENTuris_Nal.rename(columns={'Responsable nacional': 'Meta: Nombre del propietario'}, inplace=True)
ENTuris_Ext.rename(columns={'Responsable exterior': 'Meta: Nombre del propietario'}, inplace=True)

ENTuris = ENTuris_Nal.append(ENTuris_Ext)
ENTuris['Meta: Tipo de meta'] = 'Número de empresas con servicios en turismo'

In [552]:
ENTuris
#ENTuris_Ext.loc[ENTuris_Ext['Meta: Nombre del propietario'] == 'Andrea Daza Aldana']

,Meta: Nombre del propietario,Id empresa,Meta: Tipo de meta
0,Ana Maria Aguirre Escobar,1,Número de empresas con servicios en turismo
1,Ana Maria Manrique Guerrero,4,Número de empresas con servicios en turismo
2,Camila Cuadros Sundquist,6,Número de empresas con servicios en turismo
3,Carlos Mario Gonzalez Velasquez,9,Número de empresas con servicios en turismo
4,Daniela Mesa (Vacante),8,Número de empresas con servicios en turismo
...,...,...,...
30,Rosa Carolina Garzón Rodriguez,3,Número de empresas con servicios en turismo
31,Santiago De los Rios Cardona,4,Número de empresas con servicios en turismo
32,Sohee Ahn,1,Número de empresas con servicios en turismo
33,Toko Tamaki (Inv),9,Número de empresas con servicios en turismo
34,Valeria Bucheli Moncayo,27,Número de empresas con servicios en turismo

In [553]:
TFinal = TFinal.merge(ENTuris, how='left', left_on=['Meta: Nombre del propietario' , 'Meta: Tipo de meta'], 
                      right_on=['Meta: Nombre del propietario' , 'Meta: Tipo de meta']).fillna(0)


TFinal['Valor'] = TFinal['Valor'] + TFinal['Id empresa']
TFinal = TFinal.drop(columns=['Id empresa'])

#### 2020

In [554]:
ENTuris_NalA = ENacionales_NacionalA.groupby(['Responsable nacional'])['Empresa'].nunique().reset_index()
ENTuris_ExtA = ENacionales_ExteriorA.groupby(['Responsable exterior'])['Empresa'].nunique().reset_index()

ENTuris_NalA.rename(columns={'Responsable nacional': 'Meta: Nombre del propietario'}, inplace=True)
ENTuris_ExtA.rename(columns={'Responsable exterior': 'Meta: Nombre del propietario'}, inplace=True)

ENTurisA = ENTuris_NalA.append(ENTuris_ExtA)
ENTurisA['Meta: Tipo de meta'] = 'Número de empresas con servicios en turismo'

In [555]:
TFinal = TFinal.merge(ENTurisA, how='left', left_on=['Meta: Nombre del propietario' , 'Meta: Tipo de meta'], 
                      right_on=['Meta: Nombre del propietario' , 'Meta: Tipo de meta']).fillna(0)


TFinal['Valor 2020'] = TFinal['Valor 2020'] + TFinal['Empresa']
TFinal = TFinal.drop(columns=['Empresa'])

##### Eliminando los que tienen resultados pero no metas --> how ='left'

### Número de empresas PyA con primer acercamiento comercial

In [556]:
Enacionales2020 = Enacionales4.drop(Enacionales4[Enacionales4['Tipo empresa'] !=  'Nacional'].index)
Enacionales2020 = Enacionales2020.drop(Enacionales2020[Enacionales2020['Tipo registro'] !=  'MACRORRUEDAS Y ENCUENTROS COMERCIALES'].index)
Enacionales2020 = Enacionales2020[['Responsable nacional','Empresa']]
#Enacionales2020 = Enacionales2020.drop_duplicates()
Enacionales2020['Acercamiento en 2020'] = 1

#EmpresasAcercamiento = Enacionales4.groupby(['Responsable nacional' , 'Empresa'])['Pais cuenta Principal'].count().reset_index()

Enacionales2021 = ENacionales2.drop(ENacionales2[ENacionales2['Tipo empresa'] !=  'Nacional'].index)
Enacionales2021 = Enacionales2021.drop(Enacionales2021[Enacionales2021['Tipo registro'] !=  'MACRORRUEDAS Y ENCUENTROS COMERCIALES'].index)
Enacionales2021 = Enacionales2021[['Responsable nacional','Empresa']]
#Enacionales2021 = Enacionales2021.drop_duplicates()


EmpresasPrimerAcercamiento = Enacionales2021.merge(Enacionales2020, how='left', left_on=['Responsable nacional','Empresa'], 
                      right_on=['Responsable nacional','Empresa']).fillna(0)

EmpresasPrimerAcercamiento = EmpresasPrimerAcercamiento.drop_duplicates(subset=['Empresa'])

EmpresasPrimerAcercamiento = EmpresasPrimerAcercamiento.drop(EmpresasPrimerAcercamiento[EmpresasPrimerAcercamiento['Acercamiento en 2020'] == 1].index)
EmpresasPrimerAcercamiento = EmpresasPrimerAcercamiento.groupby(['Responsable nacional'])['Empresa'].nunique().reset_index()

EmpresasPrimerAcercamiento['Meta: Tipo de meta'] = 'Número de empresas PyA con primer acercamiento comercial'

EmpresasPrimerAcercamiento.rename(columns={'Responsable nacional': 'Meta: Nombre del propietario'}, inplace=True)

EmpresasPrimerAcercamiento = EmpresasPrimerAcercamiento.drop_duplicates(subset=['Empresa'])

TFinal = TFinal.merge(EmpresasPrimerAcercamiento, how='left', left_on=['Meta: Nombre del propietario' , 'Meta: Tipo de meta'], 
                      right_on=['Meta: Nombre del propietario' , 'Meta: Tipo de meta']).fillna(0)


TFinal['Valor'] = TFinal['Valor'] + TFinal['Empresa']
TFinal = TFinal.drop(columns=['Empresa'])

In [557]:
EmpresasPrimerAcercamiento = Enacionales2021.merge(Enacionales2020, how='left', left_on=['Responsable nacional','Empresa'], 
                      right_on=['Responsable nacional','Empresa']).fillna(0)

EmpresasPrimerAcercamiento = EmpresasPrimerAcercamiento.drop_duplicates(subset=['Empresa'])

EmpresasPrimerAcercamiento = EmpresasPrimerAcercamiento.drop(EmpresasPrimerAcercamiento[EmpresasPrimerAcercamiento['Acercamiento en 2020'] == 1].index)

### Número de frecuencias

#### 2021

In [558]:
frec = {'Meta: Tipo de meta':  ['Número de frecuencias'],
        'Frecuencias': [frecuencias]}

Frec = pd.DataFrame(frec)
Frec

      Meta: Tipo de meta  Frecuencias
0  Número de frecuencias         1160

In [559]:
#Frecuencias['Meta: Tipo de meta'] = 'Número de frecuencias'

In [560]:
#FrecT = Frecuencias.groupby(['Meta: Tipo de meta'])['Frecuencias'].sum().reset_index()

TFinal = TFinal.merge(Frec, how='left', left_on=[ 'Meta: Tipo de meta'], 
                      right_on=['Meta: Tipo de meta']).fillna(0)


TFinal['Valor'] = TFinal['Valor'] + TFinal['Frecuencias']
TFinal = TFinal.drop(columns=['Frecuencias'])

### Número de sillas

#### 2021

In [561]:
#Frecuencias['Meta: Tipo de meta'] = 'Número de sillas'

sillas = {'Meta: Tipo de meta':  ['Número de sillas'],
        'sillas': [nsillas]}
Sillas = pd.DataFrame(sillas)
Sillas

  Meta: Tipo de meta  sillas
0   Número de sillas  199579

In [562]:
#FrecT2 = Frecuencias.groupby(['Meta: Tipo de meta'])['Sillas'].sum().reset_index()

In [563]:
#SillasyFrecuencias2020 = SillasyFrecuencias2020.rename(columns = {'INDICADOR' : 'Meta: Tipo de meta'})

In [564]:
#TFinal = TFinal.merge(FrecT2, how='left', left_on=[ 'Meta: Tipo de meta'], 
 #                     right_on=['Meta: Tipo de meta']).fillna(0)
TFinal = TFinal.merge(Sillas, how='left', left_on=[ 'Meta: Tipo de meta'], 
                      right_on=['Meta: Tipo de meta']).fillna(0)

TFinal['Valor'] = TFinal['Valor'] + TFinal['sillas']
TFinal = TFinal.drop(columns=['sillas'])
#
#TFinal['Valor 2020'] = TFinal['Valor 2020'] + TFinal[2020]
#TFinal = TFinal.drop(columns=[2020 , 'ASESOR'])
#
#TFinal = TFinal.drop(TFinal[TFinal['Meta Total'] ==  0].index)

#TFinalEXT = TFinal.drop(TFinal[TFinal['Meta: Tipo meta funcionario'] !=  'EXTERIOR'].index)

### Proyecto de gestión

### 2021

In [565]:
ProyectoseHitos['Hito: Fecha Inicio'] = pd.to_datetime(ProyectoseHitos['Hito: Fecha Inicio'], format='%d/%m/%Y')
ProyectoseHitos1 =  ProyectoseHitos.drop(ProyectoseHitos[ProyectoseHitos['Proyecto: Nombre'] == 'Caja de Herramientas de Innovación para el Turismo'].index)
ProyectoseHitos1 =  ProyectoseHitos1.drop(ProyectoseHitos1[ProyectoseHitos1['Proyecto: Nombre'] == 'Colombianos en el exterior 2020'].index)
#ProyectoseHitos1 =  ProyectoseHitos1.drop(ProyectoseHitos1[ProyectoseHitos1['Proyecto: Nombre'] == 'Meaningful Map'].index)
ProyectoseHitos1 =  ProyectoseHitos1.drop(ProyectoseHitos1[ProyectoseHitos1['Proyecto: Nombre'] == 'Meeting plannner 2.0'].index)
ProyectoseHitos1 =  ProyectoseHitos1.drop(ProyectoseHitos1[ProyectoseHitos1['Proyecto: Nombre'] == 'Planes regionales vicepresidencia de turismo'].index)
ProyectoseHitos1 =  ProyectoseHitos1.drop(ProyectoseHitos1[ProyectoseHitos1['Proyecto: Nombre'] == 'Programa de formación exportadora en turismo – versión hibrida'].index)
ProyectoseHitos1 =  ProyectoseHitos1.drop(ProyectoseHitos1[ProyectoseHitos1['Hito: Fecha Inicio'] < fechaactual2].index)
ProyectoseHitos_Anterior = ProyectoseHitos.drop(ProyectoseHitos[ProyectoseHitos['Hito: Fecha Inicio'] < fechaanterior2].index)
ProyectoseHitos_Anterior = ProyectoseHitos_Anterior.drop(ProyectoseHitos_Anterior[ProyectoseHitos_Anterior['Hito: Fecha Inicio'] >= fechaactual2].index)


ProyectoseHitos_Anterior = ProyectoseHitos_Anterior.dropna(subset=['Hito: Fecha Inicio'])
#ProyectoseHitos1 = ProyectoseHitos

In [566]:
#ProyectoseHitos1[ProyectoseHitos1['Proyecto: Propietario'] == 'María Muñoz Rey']

In [567]:
PG = ProyectoseHitos1.groupby(['Proyecto: Propietario' , 'Proyecto: Nombre' , 
                   'Hito: Nombre'])['Hito: Peso'].sum().reset_index()
PG2 = ProyectoseHitos1.groupby(['Proyecto: Propietario' , 'Proyecto: Nombre' , 
                   'Hito: Nombre'])['Hito: Avance'].sum().reset_index()

In [568]:
PGF = PG.merge(PG2, how='outer', left_on=['Proyecto: Propietario' , 'Proyecto: Nombre' , 
                   'Hito: Nombre'], right_on=['Proyecto: Propietario' , 'Proyecto: Nombre' , 
                   'Hito: Nombre']).fillna(0)
PGF['Avance Ponderado'] = (PGF['Hito: Peso']*0.1) * (PGF['Hito: Avance']*0.1)

PGFF = PGF.groupby(['Proyecto: Propietario'])['Avance Ponderado'].sum().reset_index()
PGFF['Meta: Tipo de meta'] = 'Proyecto de gestión'
PGFF.rename(columns={'Oportunidad: Consecutivo': 'Valor Real'}, inplace=True)

In [569]:
PGFF.rename(columns={'Proyecto: Propietario': 'Meta: Nombre del propietario'}, inplace=True)

In [570]:
PGFF['Avance Ponderado'] = PGFF['Avance Ponderado']*100

In [571]:
TFinal2 = TFinal.merge(PGFF, how='outer', left_on=['Meta: Nombre del propietario', 'Meta: Tipo de meta'], 
                      right_on=['Meta: Nombre del propietario', 'Meta: Tipo de meta']).fillna(0)

In [572]:
TFinal = TFinal2

In [573]:
#TFinal2 =  TFinal2.drop(TFinal2[TFinal2['Meta Total'] == 0].index).reset_index()

#TFinal[TFinal['Meta: Tipo de meta'] == 'Proyecto de gestión']

In [574]:
TFinal

,Meta: Tipo meta funcionario,E_Localización,E_Clasificación,Meta: Nombre del propietario,E_Rol,Tipo de Indicador,Meta: Tipo de meta,Meta Total,Meta Q,Valor 2020,Valor,Avance Ponderado
0,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Comercial,Captación de Congresos y Eventos,11.0,7.0,8.0,6.00,0.00
1,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Comercial,Monto de gasto de noches,1800000.0,700000.0,1656146.0,441500.03,0.00
2,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Comercial,Monto de gasto paquetes,517850.0,140000.0,450304.0,413383.00,0.00
3,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Gestión,Número asistentes PFE turismo,1040.0,540.0,0.0,0.00,0.00
4,COLOMBIA,Barranquilla,Ofireg,Vanessa Botero Botero,Asesor regional,Gestión,Número de empresas con servicios en turismo,80.0,25.0,39.0,10.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...
160,0,0,0,Nicolas Casasfranco Jimenez,0,0,Captación de Congresos y Eventos,0.0,0.0,1.0,0.00,0.00
161,0,0,0,Dasseira Tannyt Vega Guarín (vacante),0,0,Monto de gasto paquetes,0.0,0.0,6000.0,0.00,0.00
162,0,0,0,Juan Sebastian Sanchez Chica,0,0,Proyecto de gestión,0.0,0.0,0.0,0.00,0.25
163,0,0,0,Manuela Jara Blanco,0,0,Proyecto de gestión,0.0,0.0,0.0,0.00,0.23
164,0,0,0,Sofia Navas Nuñez(VACANTE),0,0,Proyecto de gestión,0.0,0.0,0.0,0.00,0.38

In [575]:
TFinal['Valor'] = TFinal['Valor'] + TFinal['Avance Ponderado']
TFinal = TFinal.drop(columns=['Avance Ponderado'])

### 2020

In [576]:
PGA = ProyectoseHitos_Anterior.groupby(['Proyecto: Propietario' , 'Proyecto: Nombre' , 
                   'Hito: Nombre'])['Hito: Peso'].sum().reset_index()
PG2A = ProyectoseHitos_Anterior.groupby(['Proyecto: Propietario' , 'Proyecto: Nombre' , 
                   'Hito: Nombre'])['Hito: Avance'].sum().reset_index()
PGFA = PGA.merge(PG2A, how='outer', left_on=['Proyecto: Propietario' , 'Proyecto: Nombre' , 
                   'Hito: Nombre'], right_on=['Proyecto: Propietario' , 'Proyecto: Nombre' , 
                   'Hito: Nombre']).fillna(0)
PGFA['Avance Ponderado'] = (PGFA['Hito: Peso']*0.1) * (PGFA['Hito: Avance']*0.1)

PGFFA = PGFA.groupby(['Proyecto: Propietario'])['Avance Ponderado'].sum().reset_index()
PGFFA['Meta: Tipo de meta'] = 'Proyecto de gestión'
PGFFA.rename(columns={'Oportunidad: Consecutivo': 'Valor Real'}, inplace=True)
PGFFA.rename(columns={'Proyecto: Propietario': 'Meta: Nombre del propietario'}, inplace=True)
TFinal = TFinal.merge(PGFFA, how='outer', left_on=['Meta: Nombre del propietario', 'Meta: Tipo de meta'], 
                      right_on=['Meta: Nombre del propietario', 'Meta: Tipo de meta']).fillna(0)

#TFinal =  TFinal.drop(TFinal[TFinal['Meta Total'] == 0].index).reset_index()
TFinal['Valor 2020'] = TFinal['Valor 2020'] + TFinal['Avance Ponderado']
#TFinal = TFinal.drop(columns=['Avance Ponderado_x' , 'index'])

## Número asistentes PFE turismo

### 2021

In [577]:
AsistentesPFE = AsistentesPFE1
AsistentesPFE['Meta: Tipo de meta'] = 'Número asistentes PFE turismo'
AsistentesPFE.rename(columns={'ASESOR': 'Meta: Nombre del propietario',
                             'RESULTADO': 'ValorPFE'}, inplace=True)
#AsistentesPFE = AsistentesPFE.drop(columns=['Oficina' , 'Meta Año' , 'Avance' , 'Meta  4Q'])

### 2020

In [578]:
AsistentesPFE2020.rename(columns={'ASESOR': 'Meta: Nombre del propietario'}, inplace=True)

#AsistentesPFE2020 = AsistentesPFE2020.drop(columns=['Oficina' , 'Meta año 2021' , 'Meta trimestre' , 'Avance corte ' , 
 #                                                  '% avance meta año']) 

AsistentesPFE = AsistentesPFE.merge(AsistentesPFE2020, how='outer', left_on=['Meta: Nombre del propietario'] , right_on = ['Meta: Nombre del propietario']).fillna(0)

In [579]:
TFinal = TFinal.merge(AsistentesPFE, how='outer', left_on=['Meta: Nombre del propietario', 'Meta: Tipo de meta'], 
                     right_on=['Meta: Nombre del propietario', 'Meta: Tipo de meta']).fillna(0)
TFinal['Valor'] = TFinal['Valor'] + TFinal['ValorPFE']
TFinal['Valor 2020'] = TFinal['Valor 2020'] + TFinal['RESULTADO2021']

TFinal = TFinal.drop(columns=['ValorPFE' , 'RESULTADO2021'])

### VPT Visitantes no residentes

In [580]:

visitantes = {'Meta: Tipo de meta':  ['VPT Visitantes no residentes']}
Visitantes = pd.DataFrame(visitantes)
Visitantes


#InfoResponsanles = TFinalEXT[['Meta: Tipo meta funcionario', 'E_HUB2019', 'E_Localización' , 'E_Clasificación',
 #                       'Meta: Nombre del propietario' , 'E_Rol' , 'Tipo de Indicador' ]]

#Responsables=TFinalEXT[['Meta: Nombre del propietario']]
#Responsables = Responsables.drop_duplicates(subset = ['Meta: Nombre del propietario'])
#Responsables = Responsables.reset_index()
#TFinal['Meta: Tipo de meta'] = 'VPT Visitantes no residentes'

#Responsables = Responsables.merge(InfoResponsanles, how='left', left_on=['Meta: Nombre del propietario'], 
 #                     right_on=['Meta: Nombre del propietario']).fillna(0)
#Responsables = Responsables.drop_duplicates(subset = ['Meta: Nombre del propietario'])
#Responsables = Responsables.reset_index()

TFinal = TFinal.append(Visitantes)
TFinal.loc[TFinal['Meta: Tipo de meta'] == 'VPT Visitantes no residentes', 'Valor 2020'] =  mVisitanterior 
TFinal.loc[TFinal['Meta: Tipo de meta'] == 'VPT Visitantes no residentes', 'Meta Total'] =  mVisitantes
TFinal.loc[TFinal['Meta: Tipo de meta'] == 'VPT Visitantes no residentes', 'Meta Q'] =  mqVisitantes 
TFinal.loc[TFinal['Meta: Tipo de meta'] == 'VPT Visitantes no residentes', 'Valor'] =  nVisitantes 
#TFinal = TFinal.drop(columns=['Avance Ponderado'])

In [581]:
TFinal =  TFinal.drop(TFinal[TFinal['E_Rol'] == 'Profesional Turismo'].index)
TFinal.rename(columns={'Valor': 'Valor 2022' ,'Valor 2020' : 'Valor 2021'}, inplace=True)
TFinal = TFinal.drop(columns=['Avance Ponderado'])

In [582]:
TFinal = TFinal.drop(TFinal[TFinal['Meta: Tipo de meta'] == 'Número de noches'].index)
TFinal = TFinal.drop(TFinal[TFinal['Meta: Tipo de meta'] == 'Número de paquetes'].index)
TFinal = TFinal.drop(TFinal[TFinal['Meta: Tipo de meta'] == 'Monto Estimado Gasto U$'].index)

In [583]:
#Validación
#ppp = Negocios.drop(Negocios[Negocios['Logro: Eje'] !=  'Turismo'].index)
#ppp = ppp.drop(ppp[ppp['Logro: Tipo de registro'] !=  'Captación de Eventos'].index)
#ppp = ppp.drop(ppp[ppp['E_Año'] !=  2022].index)
#ppp


#ppp.groupby(['Logro: Responsable Colombia', 
 #                'Logro: Responsable en el Exterior 1'])['Logro: Valor'].sum().reset_index()
    
    #TFinal.loc[TFinal['Meta: Tipo de meta'] == 'Monto Estimado Gasto U$']

In [584]:
writer = pd.ExcelWriter('Turismo.xlsx')
TFinal.to_excel(writer)
writer.save()
from IPython.display import FileLink
FileLink('Turismo.xlsx')

E:\Usuario\pplaneacion\Documents\Códigos Python\Turismo.xlsx

In [585]:
#TFinal[TFinal['Meta: Tipo de meta'] == 'VPT Visitantes no residentes']
#TFinal.loc[TFinal['Meta: Tipo de meta'] == 'Número de oportunidades en etapa 0 y 1']