
# Tablero Como vamos
## Vicepresidencia de Planeación - Inversión

In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import matplotlib as mpl 
import six
import os 

pathout = './data/'
if not os.path.exists(pathout):
    os.mkdir(pathout) 
    pathgraphs = './graphs/'
    if not os.path.exists(pathgraphs): 
        os.mkdir(pathgraphs)

In [2]:
import datetime
from datetime import datetime

In [72]:
Metas = pd.read_excel(pathout + 'MetasMayo.xlsx')

In [73]:
Negocios = pd.read_excel(pathout + 'NegociosMayo.xlsx')

In [74]:
Oportunidades = pd.read_excel(pathout + 'OportunidadesMayo.xlsx')

In [86]:
OportunidadesRegionales = pd.read_excel(pathout + '(Sólo 2022) Oportunidades Regionales IED a Mayo 2022.xlsx')

In [151]:
PotafolioProyectos = pd.read_excel(pathout + '(Sólo 2022) Proyectos portafolio de oportunidades IED a Mayo 2022.xlsx')

In [77]:
ENacionales = pd.read_excel(pathout + 'Enacionales3mayo.xlsx')

In [78]:
#Cambio_Etapa = pd.read_excel(pathout + 'CE15may.xlsx')

In [79]:
Cambio_Etapa = pd.read_excel(pathout + '(Sólo 2022) Cambio de etapa oportunidades IED e ICE a Mayo 2022.xlsx')

In [11]:
#ServiciosCovid = pd.read_excel(pathout + 'Reporte 3 Ejes (servicios+tareas+eventos).xlsx')

In [95]:
#FuncionarioHub = pd.read_excel(pathout + 'Correlativa funcionario hub.xlsx')

In [96]:
#OficinasHub = pd.read_excel(pathout + 'Oficinas hub.xlsx')

# Parte 1

In [97]:
Negocios['Logro: Cadena Productiva'] = Negocios['Logro: Cadena Productiva'].str.lower()
Negocios['E_LocalizaciónCOL'] = Negocios['E_LocalizaciónCOL'].str.lower()
Negocios['E_Cadenasproductivas'] = Negocios['E_Cadenasproductivas'].str.lower()
Negocios['Logro: Responsable Colombia'] = Negocios['Logro: Responsable Colombia'].str.lower()
Negocios['E_regionalIED'] = Negocios['E_regionalIED'].str.lower()
Negocios['Logro: Oficina Comercial'] = Negocios['Logro: Oficina Comercial'].str.lower()
Negocios['Logro: Responsable en el Exterior 1'] = Negocios['Logro: Responsable en el Exterior 1'].str.lower()
#Negocios['Tenant'].replace('', np.nan, inplace=True)

#Donde dice Inversion Instalada y donde Monto?
#    Monto de Inversión
    
    
Cambio_Etapa['Responsable en Colombia'] = Cambio_Etapa['Responsable en Colombia'].str.lower()
Cambio_Etapa['Cadena productiva'] = Cambio_Etapa['Cadena productiva'].str.lower()

Metas['Meta: Nombre del propietario'] = Metas['Meta: Nombre del propietario'].str.lower()
Metas['E_Localización'] = Metas['E_Localización'].str.lower()
Metas['E_Cadenas'] = Metas['E_Cadenas'].str.lower()


PotafolioProyectos['Responsable Regional'] = PotafolioProyectos['Responsable Regional'].str.lower()

OportunidadesRegionales['Oportunidad: ¿Que usuario identificó?'] = OportunidadesRegionales['Oportunidad: ¿Que usuario identificó?'].str.lower()

### Monto de Inversión solo por gerencia y cadena

In [98]:
añoactual = 2022
trimestre = 2

fechaetapa = '31/12/2021' #Esta fecha es para eliminar lo menor a 2022 en la base de cambio de etapa
fechaetapa2 = '02/05/2022' 
fecha2 = '31/12/2021' 

#Fecha en Formato aaaa/mm/dd para la base de Tableau 12a
negociosañoactual = '2022-01-01'
fechaactual  = '2022-05-02'
fechaactual2  = '1/01/2022'

In [99]:
Metas1 = Metas.drop(Metas[Metas['Meta: Eje'] != 'Inversión'].index)
Metas1 = Metas1.drop(Metas1[Metas1['Meta: Año'] !=  añoactual].index)
Metas1 = Metas1.drop(Metas1[Metas1['Meta: Tipo meta funcionario'] != 'COLOMBIA'].index)
MetasQ = Metas1.drop(Metas1[Metas1['Meta: Período'] > trimestre].index)

In [100]:
a = Metas1.groupby(['E_Localización' , 'Meta: Tipo de meta' , 'E_Cadenas' ])['Meta: Valor meta'].sum().reset_index()
a2 = MetasQ.groupby(['E_Localización' , 'Meta: Tipo de meta' , 'E_Cadenas' ])['Meta: Valor meta'].sum().reset_index()

In [101]:
Metasdf = a.merge(a2, how='outer', left_on=['E_Localización' ,  'Meta: Tipo de meta' , 'E_Cadenas'], right_on=['E_Localización' , 'Meta: Tipo de meta' , 'E_Cadenas']).fillna(0)
Metasdf.rename(columns={'Meta: Valor meta_x': 'Valor Meta', 'Meta: Valor meta_y': 'Valor Meta Q'}, inplace=True)

### Monto de Inversión solo por gerencia y cadena

In [102]:
Negocios1 = Negocios.drop(Negocios[Negocios['Logro: Eje'] != 'Inversión'].index)
Negocios1 = Negocios1.drop(Negocios1[Negocios1['Meta 1 responsable Colombia: Año'] !=  añoactual].index)
Negocios1 = Negocios1.drop(Negocios1[Negocios1['Logro: Tipo de registro'] !=  'Monto de Inversión'].index)

In [103]:
b = Negocios1.groupby(['E_LocalizaciónCOL' , 'E_Cadenasproductivas'])['Logro: Valor'].sum().reset_index()
b['Meta: Tipo de meta']= 'Monto de Inversión'
b.rename(columns={'E_LocalizaciónCOL' : 'E_Localización' , 'E_Cadenasproductivas':'E_Cadenas'}, inplace=True)

In [104]:
b

,E_Localización,E_Cadenas,Logro: Valor,Meta: Tipo de meta
0,gerencia inversión asia,agroalimentos,1.050000e+06,Monto de Inversión
1,gerencia inversión asia,competitividad,3.110000e+08,Monto de Inversión
2,gerencia inversión asia,industrias 4.0,7.000000e+06,Monto de Inversión
3,gerencia inversión asia,metalmecánica y otras industrias,7.000000e+06,Monto de Inversión
4,gerencia inversión asia,químicos y ciencias de la vida,8.000000e+06,Monto de Inversión
5,gerencia inversión asia,turismo y otros,1.201500e+08,Monto de Inversión
6,gerencia inversión europa,competitividad,1.086659e+09,Monto de Inversión
7,gerencia inversión europa,industrias 4.0,1.972653e+07,Monto de Inversión
8,gerencia inversión europa,metalmecánica y otras industrias,4.500000e+06,Monto de Inversión
9,gerencia inversión europa,químicos y ciencias de la vida,5.000000e+06,Monto de Inversión
10,gerencia inversión europa,turismo y otros,6.000000e+07,Monto de Inversión
11,gerencia inversión latinoamérica,agroalimentos,1.530000e+07,Monto de Inversión
12,gerencia inversión latinoamérica,competitividad,1.038082e+09,Monto de Inversión
13,gerencia inversión latinoamérica,industrias 4.0,2.119839e+07,Monto de Inversión
14,gerencia inversión latinoamérica,metalmecánica y otras industrias,3.000000e+05,Monto de Inversión
15,gerencia inversión latinoamérica,químicos y ciencias de la vida,8.140000e+07,Monto de Inversión
16,gerencia inversión latinoamérica,turismo y otros,4.738283e+08,Monto de Inversión
17,gerencia inversión norteamérica,agroalimentos,9.550000e+07,Monto de Inversión
18,gerencia inversión norteamérica,competitividad,3.000000e+08,Monto de Inversión
19,gerencia inversión norteamérica,fondos de inversión,5.500000e+07,Monto de Inversión
20,gerencia inversión norteamérica,industrias 4.0,1.056005e+08,Monto de Inversión
21,gerencia inversión norteamérica,químicos y ciencias de la vida,5.900000e+06,Monto de Inversión
22,gerencia inversión norteamérica,turismo y otros,8.228500e+07,Monto de Inversión

In [105]:
#TFinal.loc[TFinal['Meta: Tipo de meta'] == 'Monto de Inversión']

#gerencia inversión norteamérica	carolina tamayo hackmayer	
#gerencia inversión norteamérica	carolina tamayo hackmayer

In [106]:
TFinal = Metasdf.merge(b, how='left', left_on=['E_Localización' , 'E_Cadenas' , 'Meta: Tipo de meta'], right_on=['E_Localización' , 'E_Cadenas' , 'Meta: Tipo de meta']).fillna(0)

In [107]:
py = Negocios1.groupby(['E_LocalizaciónCOL' , 'E_Cadenasproductivas'])['E_ConteoProyectosInversión'].sum().reset_index()
py['Meta: Tipo de meta']= 'Proyectos Inversión'
py.rename(columns={'E_LocalizaciónCOL':'E_Localización'  , 'E_Cadenasproductivas' :'E_Cadenas' }, inplace=True)

TFinal = TFinal.merge(py, how='left', left_on=['E_Localización' , 'E_Cadenas' , 'Meta: Tipo de meta'], right_on=['E_Localización' , 'E_Cadenas' , 'Meta: Tipo de meta']).fillna(0)
TFinal['Logro: Valor'] = TFinal['Logro: Valor'] + TFinal['E_ConteoProyectosInversión']
TFinal = TFinal.drop(columns=['E_ConteoProyectosInversión'])

### Monto de Inversión Por Gerencia y Responsable

In [108]:
a = Metas1.groupby(['E_Localización' , 'Meta: Nombre del propietario' , 'Meta: Tipo de meta' , 'E_Cadenas' ])['Meta: Valor meta'].sum().reset_index()
a2 = MetasQ.groupby(['E_Localización' , 'Meta: Nombre del propietario' , 'Meta: Tipo de meta' , 'E_Cadenas' ])['Meta: Valor meta'].sum().reset_index()

In [109]:
Metasdf = a.merge(a2, how='outer', left_on=['E_Localización' , 'Meta: Nombre del propietario' ,'Meta: Tipo de meta' , 'E_Cadenas'], right_on=['E_Localización' , 'Meta: Nombre del propietario','Meta: Tipo de meta' , 'E_Cadenas']).fillna(0)
Metasdf.rename(columns={'Meta: Valor meta_x': 'Valor Meta', 'Meta: Valor meta_y': 'Valor Meta Q'}, inplace=True)

In [110]:
Negocios1 = Negocios.drop(Negocios[Negocios['Logro: Eje'] != 'Inversión'].index)
Negocios1 = Negocios1.drop(Negocios1[Negocios1['Meta 1 responsable Colombia: Año'] !=  añoactual].index)
Negocios1 = Negocios1.drop(Negocios1[Negocios1['Logro: Tipo de registro'] !=  'Monto de Inversión'].index)

In [111]:
b = Negocios1.groupby(['E_LocalizaciónCOL' , 'Logro: Responsable Colombia', 'E_Cadenasproductivas'])['Logro: Valor'].sum().reset_index()
b['Meta: Tipo de meta']= 'Monto de Inversión'
b.rename(columns={'E_LocalizaciónCOL' : 'E_Localización' , 'E_Cadenasproductivas':'E_Cadenas' , 'Logro: Responsable Colombia': 'Meta: Nombre del propietario'}, inplace=True)

In [112]:
TFinal = Metasdf.merge(b, how='left', left_on=['E_Localización' , 'Meta: Nombre del propietario','E_Cadenas' , 'Meta: Tipo de meta'], right_on=['E_Localización', 'Meta: Nombre del propietario', 'E_Cadenas' , 'Meta: Tipo de meta']).fillna(0)

## Proyectos

In [113]:
py = Negocios1.groupby(['E_LocalizaciónCOL' ,'Logro: Responsable Colombia' , 'E_Cadenasproductivas'])['E_ConteoProyectosInversión'].sum().reset_index()
py['Meta: Tipo de meta']= 'Proyectos Inversión'
py.rename(columns={'E_LocalizaciónCOL':'E_Localización'  , 'E_Cadenasproductivas' :'E_Cadenas' , 'Logro: Responsable Colombia': 'Meta: Nombre del propietario'}, inplace=True)

TFinal = TFinal.merge(py, how='left', left_on=['E_Localización' , 'E_Cadenas' , 'Meta: Nombre del propietario' , 'Meta: Tipo de meta'], right_on=['E_Localización' , 'E_Cadenas' ,'Meta: Nombre del propietario' , 'Meta: Tipo de meta']).fillna(0)
TFinal['Logro: Valor'] = TFinal['Logro: Valor'] + TFinal['E_ConteoProyectosInversión']
TFinal = TFinal.drop(columns=['E_ConteoProyectosInversión'])

## Movimiento de Oportunidades

In [114]:
Metasoport = Metas

Metasoport = Metasoport.drop(Metasoport[Metasoport['Meta: Eje'] != 'Inversión'].index)
Metasoport = Metasoport.drop(Metasoport[Metasoport['Meta: Año'] !=  añoactual].index)
Metasoport = Metasoport.drop(Metasoport[Metasoport['Tipo de Indicador'] !=  'Gestión'].index)
Metasoport = Metasoport.drop(Metasoport[Metasoport['Meta: Tipo meta funcionario'] !=  'COLOMBIA'].index)
Metasoport = Metasoport.drop(Metasoport[Metasoport['Meta: Período'] !=  trimestre].index)

In [115]:
Metasoport = Metasoport.groupby(['E_Localización' ,'Meta: Nombre del propietario' ,'Meta: Tipo de meta'])['Meta: Valor meta'].sum().reset_index()

In [116]:
Cambio_Etapa2 = Cambio_Etapa.drop(Cambio_Etapa[Cambio_Etapa['Campo / Evento'] != 'Creado.'].index)

Cambio_Etapa2 = Cambio_Etapa2.drop(Cambio_Etapa2[Cambio_Etapa2['Oportunidad: Fecha de creación'] < fechaetapa].index)
Cambio_Etapa2 = Cambio_Etapa2.drop(Cambio_Etapa2[Cambio_Etapa2['Oportunidad: Fecha de creación'] > fechaetapa2].index)


CE = Cambio_Etapa2.groupby(['Oportunidad: Consecutivo de la Oportunidad' , 'Oficina comercial 1' , 'Responsable en el exterior 1',
                      'Responsable en Colombia' , 'Cadena productiva' , 'Etapa'])['Valor nuevo'].sum().reset_index()
CE = CE.drop(columns=['Valor nuevo'])

In [117]:
Cambio_Etapa2 = Cambio_Etapa.drop(Cambio_Etapa[Cambio_Etapa['Oportunidad: Fecha de creación'] < fechaetapa].index)
Cambio_Etapa2 = Cambio_Etapa2.drop(Cambio_Etapa2[Cambio_Etapa2['Eje'] != 'Inversión'].index)


CE2 =  Cambio_Etapa2.groupby(['Oportunidad: Consecutivo de la Oportunidad' , 'Oficina comercial 1' , 'Responsable en el exterior 1',
                      'Responsable en Colombia' , 'Cadena productiva' , 'Etapa' , 'Campo / Evento' , 'Fecha de modificación' ,
                             'Valor anterior' , 'Valor nuevo'])['Valor de Logros Certificados'].count().reset_index()
CE2 = CE2.drop(columns=['Valor de Logros Certificados']) 

colkeep = 'Oportunidad: Consecutivo de la Oportunidad' , 'Valor anterior'

CE2 = CE2.loc[:, colkeep]
CE2.rename(columns={'Valor anterior': 'Etapa creación'}, inplace=True)

CE2 = CE2.drop_duplicates(subset='Oportunidad: Consecutivo de la Oportunidad', keep='first')

In [118]:
#CE_Principal.loc[CE_Principal['Oportunidad: Consecutivo de la Oportunidad'] == 'Oportunidad-335932']

In [119]:
CE3 = CE
CE3['Etapa en la que se creo'] = 0
CE3.loc[CE3['Etapa'] == 0, 'Etapa en la que se creo'] = 0
CE_Principal = Cambio_Etapa2.groupby(['Oportunidad: Consecutivo de la Oportunidad' , 'Oficina comercial 1' , 'Responsable en el exterior 1',
                      'Responsable en Colombia' , 'Cadena productiva' , 'Etapa'])['Valor nuevo'].sum().reset_index()
CE_Principal = CE_Principal.drop(columns=['Valor nuevo']) 
CE_Principal
CE_Principal = CE_Principal.merge(CE2, how='left', left_on=['Oportunidad: Consecutivo de la Oportunidad'],
                right_on=['Oportunidad: Consecutivo de la Oportunidad']).fillna('-')

In [120]:
CE_Principal.loc[CE_Principal['Etapa creación'] == '-', 'Etapa creación'] = CE_Principal['Etapa']

In [121]:
CE_Principal
CE_Principal.loc[CE_Principal['Responsable en Colombia'] == 'christian javier paz lopez']

,Oportunidad: Consecutivo de la Oportunidad,Oficina comercial 1,Responsable en el exterior 1,Responsable en Colombia,Cadena productiva,Etapa,Etapa creación
17,Oportunidad-336167,China,Margarita Quan,christian javier paz lopez,metalmecánica y otras industrias,1,0.0
22,Oportunidad-336411,Corea (Sur) Rep de,Sohee Ahn,christian javier paz lopez,otros,0,0
29,Oportunidad-336649,Indonesia,Beatriz Eugenia Barreto Escobar,christian javier paz lopez,turismo,1,0.0
55,Oportunidad-337990,Japón,Toko Tamaki (Inv),christian javier paz lopez,otros,1,0.0
58,Oportunidad-338025,India,Juan Esteban Sanchez Sanchez,christian javier paz lopez,metalmecánica y otras industrias,1,0.0
84,Oportunidad-338377,China,Margarita Quan,christian javier paz lopez,metalmecánica y otras industrias,1,0.0
85,Oportunidad-338564,China,Gloria Shuang Zhu,christian javier paz lopez,otros,1,0.0
87,Oportunidad-338571,Singapur,Sandra Janneth Salamanca Rosas,christian javier paz lopez,metalmecánica y otras industrias,3,0.0
98,Oportunidad-338923,China,Amanda Shi,christian javier paz lopez,metalmecánica y otras industrias,1,0.0
100,Oportunidad-339102,China,Gloria Shuang Zhu,christian javier paz lopez,otros,2,0.0
104,Oportunidad-339240,China,Gloria Shuang Zhu,christian javier paz lopez,metalmecánica y otras industrias,3,0.0
156,Oportunidad-339626,China,Margarita Quan,christian javier paz lopez,metalmecánica y otras industrias,0,0
175,Oportunidad-339807,China,Amanda Shi,christian javier paz lopez,metalmecánica y otras industrias,1,0.0
190,Oportunidad-339970,Singapur,Sandra Janneth Salamanca Rosas,christian javier paz lopez,metalmecánica y otras industrias,0,0
212,Oportunidad-340194,Corea (Sur) Rep de,Sohee Ahn,christian javier paz lopez,otros,4,0.0
213,Oportunidad-340201,Japón,Toko Tamaki (Inv),christian javier paz lopez,metalmecánica y otras industrias,2,0.0
215,Oportunidad-340206,China,Margarita Quan,christian javier paz lopez,metalmecánica y otras industrias,2,0.0
219,Oportunidad-340230,China,Gloria Shuang Zhu,christian javier paz lopez,otros,4,0.0
258,Oportunidad-340579,China,Gloria Shuang Zhu,christian javier paz lopez,metalmecánica y otras industrias,1,0.0
263,Oportunidad-340800,China,Gloria Shuang Zhu,christian javier paz lopez,otros,0,0
287,Oportunidad-341254,China,Amanda Shi,christian javier paz lopez,metalmecánica y otras industrias,0,0
296,Oportunidad-341453,China,Margarita Quan,christian javier paz lopez,sistema moda,1,0.0
297,Oportunidad-341461,Japón,Toko Tamaki (Inv),christian javier paz lopez,metalmecánica y otras industrias,0,0
301,Oportunidad-341805,China,Amanda Shi,christian javier paz lopez,metalmecánica y otras industrias,1,0.0
305,Oportunidad-341913,India,Juan Esteban Sanchez Sanchez,christian javier paz lopez,metalmecánica y otras industrias,0,0
367,Oportunidad-350279,India,Juan Esteban Sanchez Sanchez,christian javier paz lopez,metalmecánica y otras industrias,0,0

In [122]:
#drop diferente a 0
#cruce con los que la etapa no es 0

In [123]:
#FALTA ETAPA 2 Y 3
CE_Principal_Creado_E1 = CE_Principal.drop(CE_Principal[CE_Principal['Etapa creación'] != 1].index)
CE_Principal_Creado_E1_Colombia = CE_Principal_Creado_E1.groupby(['Responsable en Colombia' , 'Cadena productiva' ])['Etapa creación'].count().reset_index()
CE_Principal_Creado_E1_Colombia

CE_Principal_Creado_E2 = CE_Principal.drop(CE_Principal[CE_Principal['Etapa creación'] != 2].index)
CE_Principal_Creado_E2_Colombia = CE_Principal_Creado_E2.groupby(['Responsable en Colombia' , 'Cadena productiva' ])['Etapa creación'].count().reset_index()
CE_Principal_Creado_E2_Colombia

CE_Principal_Creado_E3 = CE_Principal.drop(CE_Principal[CE_Principal['Etapa creación'] != 3].index)
CE_Principal_Creado_E3_Colombia = CE_Principal_Creado_E3.groupby(['Responsable en Colombia' , 'Cadena productiva' ])['Etapa creación'].count().reset_index()
CE_Principal_Creado_E3_Colombia

Empty DataFrame
Columns: [Responsable en Colombia, Cadena productiva, Etapa creación]
Index: []

In [124]:
#christian javier paz lopez
#TFinal.loc[TFinal['Meta: Tipo de meta'] == 'Monto de Inversión']

In [125]:
CE_Principal_Creado_E1 = CE_Principal.drop(CE_Principal[CE_Principal['Etapa creación'] != 1].index)
CE_Principal_Creado_E1_Exterior = CE_Principal_Creado_E1.groupby(['Responsable en el exterior 1' , 'Cadena productiva' ])['Etapa creación'].count().reset_index()
CE_Principal_Creado_E1_Exterior

CE_Principal_Creado_E2 = CE_Principal.drop(CE_Principal[CE_Principal['Etapa creación'] != 2].index)
CE_Principal_Creado_E2_Exterior = CE_Principal_Creado_E2.groupby(['Responsable en el exterior 1' , 'Cadena productiva' ])['Etapa creación'].count().reset_index()
CE_Principal_Creado_E2_Exterior

CE_Principal_Creado_E3 = CE_Principal.drop(CE_Principal[CE_Principal['Etapa creación'] != 3].index)
CE_Principal_Creado_E3_Exterior = CE_Principal_Creado_E3.groupby(['Responsable en el exterior 1' , 'Cadena productiva' ])['Etapa creación'].count().reset_index()

In [126]:
CE4 = Cambio_Etapa
CE4 = CE4.drop(CE4[CE4['Eje'] != 'Inversión'].index)
CE4 = CE4.drop(CE4[CE4['Fecha de modificación'] < fechaetapa].index)
CE4 = CE4.drop(CE4[CE4['Campo / Evento'] != 'Etapa'].index)
CE4_1 = CE4.drop(CE4[CE4['Valor nuevo'] != 1].index)
CE4_1 = CE4_1.groupby(['Responsable en Colombia' , 'Cadena productiva' ])['Oportunidad: Consecutivo de la Oportunidad'].count().reset_index()
CE4_1.rename(columns={'Oportunidad: Consecutivo de la Oportunidad': 'Etapa 1'}, inplace=True)


CE4_2 = CE4.drop(CE4[CE4['Valor nuevo'] != 2].index)
CE4_2 = CE4_2.groupby(['Responsable en Colombia' , 'Cadena productiva' ])['Oportunidad: Consecutivo de la Oportunidad'].count().reset_index()
CE4_2.rename(columns={'Oportunidad: Consecutivo de la Oportunidad': 'Etapa 2'}, inplace=True)

CE4_3 = CE4.drop(CE4[CE4['Valor nuevo'] != 3].index)
CE4_3 = CE4_3.groupby(['Responsable en Colombia' , 'Cadena productiva' ])['Oportunidad: Consecutivo de la Oportunidad'].count().reset_index()
CE4_3.rename(columns={'Oportunidad: Consecutivo de la Oportunidad': 'Etapa 3'}, inplace=True)

CE_Cambio = CE4_1.merge(CE4_2, how='outer', on=['Responsable en Colombia' , 'Cadena productiva']).fillna(0)
CE_Cambio = CE_Cambio.merge(CE4_3, how='outer', on=['Responsable en Colombia' , 'Cadena productiva']).fillna(0)

In [127]:
## Intento del puntp #3

P1 = CE_Cambio.merge(CE_Principal_Creado_E1_Colombia, how='outer', on=['Responsable en Colombia' , 'Cadena productiva']).fillna(0)
P1['Etapa 1'] = P1['Etapa 1'] + P1['Etapa creación']
P1 = P1.drop(columns=['Etapa creación'])

P1 = P1.merge(CE_Principal_Creado_E2_Colombia, how='outer', on=['Responsable en Colombia' , 'Cadena productiva']).fillna(0)
P1['Etapa 1'] = P1['Etapa 1'] + P1['Etapa creación']
P1 = P1.drop(columns=['Etapa creación'])

P1 = P1.merge(CE_Principal_Creado_E3_Colombia, how='outer', on=['Responsable en Colombia' , 'Cadena productiva']).fillna(0)
P1['Etapa 1'] = P1['Etapa 1'] + P1['Etapa creación']
P1 = P1.drop(columns=['Etapa creación'])

P1
#Si funciona!

PE1 = P1.drop(columns=['Etapa 2' , 'Etapa 3'])
PE2 = P1.drop(columns=['Etapa 1' , 'Etapa 3'])
PE3 = P1.drop(columns=['Etapa 1' , 'Etapa 2'])

In [128]:
PE1.rename(columns={'Responsable en Colombia': 'Meta: Nombre del propietario' , 
                                               'Cadena productiva': 'E_Cadenas'}, inplace=True)

PE1['Meta: Tipo de meta'] = 'Número de oportunidades de Inversión a etapa 1'
TFinal = TFinal.merge(PE1, how='left', right_on=['Meta: Nombre del propietario' , 'E_Cadenas' , 'Meta: Tipo de meta'],
                      left_on=['Meta: Nombre del propietario' , 'E_Cadenas' , 'Meta: Tipo de meta']).fillna(0)

TFinal['Logro: Valor'] = TFinal['Logro: Valor'] + TFinal['Etapa 1']
TFinal = TFinal.drop(columns=['Etapa 1'])


PE2.rename(columns={'Responsable en Colombia': 'Meta: Nombre del propietario' , 
                                               'Cadena productiva': 'E_Cadenas'}, inplace=True)

PE2['Meta: Tipo de meta'] = 'Número de oportunidades de Inversión a etapa 2'
TFinal = TFinal.merge(PE2, how='left', right_on=['Meta: Nombre del propietario' , 'E_Cadenas' , 'Meta: Tipo de meta'],
                      left_on=['Meta: Nombre del propietario' , 'E_Cadenas' , 'Meta: Tipo de meta']).fillna(0)

TFinal['Logro: Valor'] = TFinal['Logro: Valor'] + TFinal['Etapa 2']
TFinal = TFinal.drop(columns=['Etapa 2'])



PE3.rename(columns={'Responsable en Colombia': 'Meta: Nombre del propietario' , 
                                               'Cadena productiva': 'E_Cadenas'}, inplace=True)

PE3['Meta: Tipo de meta'] = 'Número de oportunidades de Inversión a etapa 3'
TFinal = TFinal.merge(PE3, how='left', right_on=['Meta: Nombre del propietario' , 'E_Cadenas' , 'Meta: Tipo de meta'],
                      left_on=['Meta: Nombre del propietario' , 'E_Cadenas' , 'Meta: Tipo de meta']).fillna(0)

TFinal['Logro: Valor'] = TFinal['Logro: Valor'] + TFinal['Etapa 3']
TFinal = TFinal.drop(columns=['Etapa 3'])

TFinal

,E_Localización,Meta: Nombre del propietario,Meta: Tipo de meta,E_Cadenas,Valor Meta,Valor Meta Q,Logro: Valor
0,gerencia inversión asia,catalina gonzalez cano,Monto de Inversión,competitividad,1.000000e+09,500000000.0,311000000.0
1,gerencia inversión asia,catalina gonzalez cano,Número de oportunidades de Inversión a etapa 1,competitividad,2.100000e+01,6.0,24.0
2,gerencia inversión asia,catalina gonzalez cano,Número de oportunidades de Inversión a etapa 2,competitividad,1.400000e+01,4.0,22.0
3,gerencia inversión asia,catalina gonzalez cano,Número de oportunidades de Inversión a etapa 3,competitividad,8.000000e+00,3.0,14.0
4,gerencia inversión asia,catalina gonzalez cano,Proyectos Inversión,competitividad,7.000000e+00,4.0,3.0
...,...,...,...,...,...,...,...
156,gerencia inversión norteamérica,maria andrea villanueva vergara (vacante),Número de oportunidades de Inversión a etapa 2,turismo y otros,5.000000e+00,3.0,0.0
157,gerencia inversión norteamérica,maria andrea villanueva vergara (vacante),Número de oportunidades de Inversión a etapa 3,químicos y ciencias de la vida,1.000000e+00,1.0,0.0
158,gerencia inversión norteamérica,maria andrea villanueva vergara (vacante),Número de oportunidades de Inversión a etapa 3,turismo y otros,2.000000e+00,2.0,0.0
159,gerencia inversión norteamérica,maria andrea villanueva vergara (vacante),Proyectos Inversión,químicos y ciencias de la vida,1.000000e+00,1.0,0.0
160,gerencia inversión norteamérica,maria andrea villanueva vergara (vacante),Proyectos Inversión,turismo y otros,3.000000e+00,3.0,3.0

In [129]:
#TFinal.loc[TFinal['Meta: Tipo de meta'] == 'Número de oportunidades de Inversión a etapa 1']

In [130]:
#Hacer el calculo solo por gerencia -> groupby

In [131]:
#TFinal.loc[TFinal['Meta: Tipo de meta'] == 'Número de oportunidades de Inversión a etapa 1']

## Regional

In [132]:
MetasR = Metas.drop(Metas[Metas['Meta: Eje'] != 'Inversión'].index)

MetasR = MetasR.drop(MetasR[MetasR['Meta: Año'] !=  añoactual].index)

MetasR = MetasR.drop(MetasR[MetasR['Meta: Tipo meta funcionario'] != 'COLOMBIA'].index)
MetasR = MetasR.drop(MetasR[MetasR['Meta: Oficina'] != 'Colombia'].index)

MetasR = MetasR.drop(MetasR[(MetasR['E_Localización'] != 'barranquilla') &                         
                                     (MetasR['E_Localización'] != 'bucaramanga') &
                                     (MetasR['E_Localización'] != 'cali') &
                                     (MetasR['E_Localización'] != 'cartagena') &
                                     (MetasR['E_Localización'] != 'cúcuta') &
                                     (MetasR['E_Localización'] != 'manizales') &
                                     (MetasR['E_Localización'] != 'medellín') &
                                     (MetasR['E_Localización'] != 'pereira')].index)


MetasQR = MetasR.drop(MetasR[MetasR['Meta: Período'] > trimestre].index)

In [133]:
aR = MetasR.groupby(['E_Localización' ,'Meta: Nombre del propietario' ,'Meta: Tipo de meta' ])['Meta: Valor meta'].sum().reset_index()
a2R = MetasQR.groupby(['E_Localización' ,'Meta: Nombre del propietario' ,'Meta: Tipo de meta'])['Meta: Valor meta'].sum().reset_index()

MetasdfR = aR.merge(a2R, how='outer', left_on=['E_Localización' ,  'Meta: Tipo de meta' , 'Meta: Nombre del propietario'], right_on=['E_Localización' , 'Meta: Tipo de meta' , 'Meta: Nombre del propietario']).fillna(0)
MetasdfR.rename(columns={'Meta: Valor meta_x': 'Valor Meta', 'Meta: Valor meta_y': 'Valor Meta Q'}, inplace=True)

In [134]:
NegociosR = Negocios.drop(Negocios[Negocios['Logro: Eje'] != 'Inversión'].index)
NegociosR = NegociosR.drop(NegociosR[NegociosR['Meta 1 responsable Colombia: Año'] !=  añoactual].index)
NegociosR = NegociosR.drop(NegociosR[NegociosR['Logro: Tipo de registro'] !=  'Monto de Inversión'].index)

In [135]:
MIR = NegociosR.groupby(['E_regionalIED' ,'Logro: Tipo de registro' ])['Logro: Valor'].sum().reset_index()
MIR.rename(columns={'E_regionalIED': 'E_Localización' , 'Logro: Tipo de registro':'Meta: Tipo de meta'  }, inplace=True)
MIR['Meta: Tipo de meta'].replace('Monto de Inversión', 'Inversión instalada', inplace=True)

Regional = MetasdfR.merge(MIR, how='left', left_on=['E_Localización' ,  'Meta: Tipo de meta' ], right_on=['E_Localización' , 'Meta: Tipo de meta']).fillna(0)

In [136]:
MetasdfR.merge(MIR, how='outer', left_on=['E_Localización' ,  'Meta: Tipo de meta' ], right_on=['E_Localización' , 'Meta: Tipo de meta']).fillna(0)

,E_Localización,Meta: Nombre del propietario,Meta: Tipo de meta,Valor Meta,Valor Meta Q,Logro: Valor
0,barranquilla,juan esteban vasquez montoya,Inversión instalada,1.140000e+09,570000000.0,2.927000e+08
1,barranquilla,juan esteban vasquez montoya,Número de nuevas oportunidades regionales etap...,1.500000e+01,5.0,0.000000e+00
2,barranquilla,juan esteban vasquez montoya,Número de proyectos de inversión de la región ...,1.000000e+01,3.0,0.000000e+00
3,bucaramanga,sandra lucia charry reyes,Inversión instalada,5.000000e+07,25000000.0,5.000000e+06
4,bucaramanga,sandra lucia charry reyes,Número de nuevas oportunidades regionales etap...,7.000000e+00,2.0,0.000000e+00
5,bucaramanga,sandra lucia charry reyes,Número de proyectos de inversión de la región ...,3.000000e+00,1.0,0.000000e+00
6,cali,katherine caicedo tapasco,Inversión instalada,1.250000e+09,625000000.0,1.224574e+09
7,cali,katherine caicedo tapasco,Número de nuevas oportunidades regionales etap...,3.000000e+01,9.0,0.000000e+00
8,cali,katherine caicedo tapasco,Número de proyectos de inversión de la región ...,1.500000e+01,5.0,0.000000e+00
9,cartagena,francisco javier vergara piñeres,Inversión instalada,1.500000e+08,75000000.0,8.528500e+07
10,cartagena,francisco javier vergara piñeres,Número de nuevas oportunidades regionales etap...,6.000000e+00,2.0,0.000000e+00
11,cartagena,francisco javier vergara piñeres,Número de proyectos de inversión de la región ...,1.000000e+01,3.0,0.000000e+00
12,cúcuta,norma elizabeth rodriguez carreño,Inversión instalada,1.000000e+05,50000.0,1.150000e+06
13,cúcuta,norma elizabeth rodriguez carreño,Número de nuevas oportunidades regionales etap...,4.000000e+00,1.0,0.000000e+00
14,cúcuta,norma elizabeth rodriguez carreño,Número de proyectos de inversión de la región ...,2.000000e+00,0.0,0.000000e+00
15,manizales,carlos mario gonzalez velasquez,Inversión instalada,2.000000e+07,10000000.0,4.500000e+06
16,manizales,carlos mario gonzalez velasquez,Número de nuevas oportunidades regionales etap...,7.000000e+00,2.0,0.000000e+00
17,manizales,carlos mario gonzalez velasquez,Número de proyectos de inversión de la región ...,5.000000e+00,1.0,0.000000e+00
18,medellín,alejandro arbelaez ramirez (vacante),Inversión instalada,9.200000e+08,460000000.0,4.072739e+07
19,medellín,alejandro arbelaez ramirez (vacante),Número de nuevas oportunidades regionales etap...,3.000000e+01,9.0,0.000000e+00
20,medellín,alejandro arbelaez ramirez (vacante),Número de proyectos de inversión de la región ...,1.000000e+01,3.0,0.000000e+00
21,pereira,eduardo andres sanchez,Inversión instalada,1.200000e+07,6000000.0,8.900000e+06
22,pereira,eduardo andres sanchez,Número de nuevas oportunidades regionales etap...,1.100000e+01,3.0,0.000000e+00
23,pereira,eduardo andres sanchez,Número de proyectos de inversión de la región ...,7.000000e+00,3.0,0.000000e+00
24,bogotá,0,Inversión instalada,0.000000e+00,0.0,2.241642e+09

### Oportunidades Regionales IED

In [137]:
OportReg = OportunidadesRegionales.drop(OportunidadesRegionales[OportunidadesRegionales['Oportunidad: Tipo de registro'] != 'Inversión'].index) 
OportReg1 = OportReg.groupby(['Oportunidad: ¿Cuál Regional?' ,'Oportunidad: ¿Que usuario identificó?' ])['Oportunidad: Consecutivo'].count().reset_index()
OportReg1['Meta: Tipo de meta'] = 'Número de nuevas oportunidades regionales etapa 0 a 4'

In [138]:
OportReg1.loc[OportReg1['Oportunidad: ¿Cuál Regional?'] == 'Oficina Regional de Barranquilla', 'Oportunidad: ¿Cuál Regional?'] = 'barranquilla'
OportReg1.loc[OportReg1['Oportunidad: ¿Cuál Regional?'] == 'Oficina Regional de Bucaramanga', 'Oportunidad: ¿Cuál Regional?'] = 'bucaramanga'
OportReg1.loc[OportReg1['Oportunidad: ¿Cuál Regional?'] == 'Oficina Regional de Cali', 'Oportunidad: ¿Cuál Regional?'] = 'cali'
OportReg1.loc[OportReg1['Oportunidad: ¿Cuál Regional?'] == 'Oficina Regional de Cartagena', 'Oportunidad: ¿Cuál Regional?'] = 'cartagena'
OportReg1.loc[OportReg1['Oportunidad: ¿Cuál Regional?'] == 'Oficina Regional de Cucuta', 'Oportunidad: ¿Cuál Regional?'] = 'cúcuta'
OportReg1.loc[OportReg1['Oportunidad: ¿Cuál Regional?'] == 'Oficina Regional de Manizales', 'Oportunidad: ¿Cuál Regional?'] = 'manizales'
OportReg1.loc[OportReg1['Oportunidad: ¿Cuál Regional?'] == 'Oficina Regional de Medellin', 'Oportunidad: ¿Cuál Regional?'] = 'medellín'
OportReg1.loc[OportReg1['Oportunidad: ¿Cuál Regional?'] == 'Oficina Regional de Pereira', 'Oportunidad: ¿Cuál Regional?'] = 'pereira'


OportReg1.rename(columns={'Oportunidad: ¿Cuál Regional?': 'E_Localización' ,'Oportunidad: ¿Que usuario identificó?':'Meta: Nombre del propietario' ,'Logro: Tipo de registro':'Meta: Tipo de meta'  }, inplace=True)

In [139]:
Regional = Regional.merge(OportReg1, how='outer', left_on=['E_Localización' ,  'Meta: Tipo de meta' , 'Meta: Nombre del propietario'], right_on=['E_Localización' , 'Meta: Tipo de meta' , 'Meta: Nombre del propietario']).fillna(0)
Regional['Resultado'] = Regional['Logro: Valor'] + Regional['Oportunidad: Consecutivo']
Regional = Regional.drop(columns=['Logro: Valor' , 'Oportunidad: Consecutivo'])

### Portafolio de proyectos
Número de proyectos de inversión de la región - Banco de proyectos

In [140]:
PotafolioProyectos

,Portafolio de oportunidades: Consecutivo,Nombre del proyecto,Responsable Regional,Portafolio de oportunidades: Id.,Portafolio de oportunidades: Fecha de creación,año,Empresa o entidad encargada,Descripción de la empresa,Estado Aprobacion,Ciudad-Departamento,Portafolio de oportunidades: Tipo de registro,Portafolio de oportunidades: Creado por
0,BPI-0000177,NaN,jacqueline molina ospina (vacante),a2q0y000002ueTo,2020-08-20,2020,bussnies consulting corporation sas,Empresa con mas de 16 años de experiencia dedi...,PENDIENTE,Tumaco - Nariño,RealEstate,Miguel Angel Nuñez Aguilar
1,BPI-0000398,NaN,jaime alberto torres carranza (vacante),a2q4X000012PTCH,2022-02-08,2022,Cadena de Pastelerías,Cadena de pastelerias de cobertura nacional co...,PENDIENTE,Medellín - Antioquia,Agroindustria,Mauricio Serna
2,BPI-0000400,NaN,jaime alberto torres carranza (vacante),a2q4X000012PTum,2022-02-08,2022,Empresa de Lacteos,Empresa de lacteos de Cali con alta diversific...,PENDIENTE,Cali - Valle del Cauca,Agroindustria,Mauricio Serna
3,BPI-0000361,NaN,jaime alberto torres carranza (vacante),a2q4X00000xuXGe,2021-07-20,2021,Boato Hotel Sas,Eco Hotel 5 estrellas con 1 año de operación. ...,PENDIENTE,Guatape - Antioquia,Turismo,Camilo Arango
4,BPI-0000350,NaN,jaime alberto torres carranza (vacante),a2q4X00000xuXG0,2021-06-30,2021,PISCICOLA DE OCCIDENTE SAS,"Empresa colombiana, familiar, principales expo...",PENDIENTE,Bello - Antioquia,Agroindustria,Alvaro Arenas Serna
...,...,...,...,...,...,...,...,...,...,...,...,...
365,BPI-0000109,NaN,NaN,a2q0y000002yw54,2020-05-05,2020,Grupo Empresarial Agroindustrial (Proyecto Ver...,Posibilidad de que un inversionista adquiera ...,CANCELADO,Santa Rosalia - Vichada,Agroindustria,Lina Maria Patarroyo Castillo (VACANTE)
366,BPI-0000108,NaN,NaN,a2q0y000002yw4z,2020-05-05,2020,Casa Luker,Plantación de campo verde Desarrollo de Cacao ...,CANCELADO,Colombia - Huila,Agroindustria,Lina Maria Patarroyo Castillo (VACANTE)
367,BPI-0000269,El Copey,NaN,a2q4X00000v92My,2021-03-08,2021,Latamsolar,NaN,CANCELADO,El Copey - Cesar,Energia,Laura Veloza Blanco (vacante)
368,BPI-0000271,La Loma,NaN,a2q4X00000v92N3,2021-03-08,2021,Latamsolar,NaN,CANCELADO,La Loma - Cesar,Energia,Laura Veloza Blanco (vacante)
369,BPI-0000272,Sabanalarga,NaN,a2q4X00000v92N4,2021-03-08,2021,Latamsolar,NaN,CANCELADO,Sabanalarga - Casanare,Energia,Laura Veloza Blanco (vacante)

In [141]:
PProy = PotafolioProyectos.drop(PotafolioProyectos[PotafolioProyectos['año'] != añoactual].index)
PProy = PProy.drop(PProy[PProy['Estado Aprobacion'] != 'APROBADO'].index)

pp = PProy.groupby(['Portafolio de oportunidades: Consecutivo' , 'Responsable Regional' , 'Empresa o entidad encargada'])['Ciudad-Departamento'].count().reset_index()
pp = pp.groupby(['Responsable Regional'])['Portafolio de oportunidades: Consecutivo'].nunique().reset_index()
pp.rename(columns={'Responsable Regional': 'Meta: Nombre del propietario'}, inplace=True)

pp['Meta: Tipo de meta'] = 'Número de proyectos de inversión de la región - Banco de proyectos'

pp

,Meta: Nombre del propietario,Portafolio de oportunidades: Consecutivo,Meta: Tipo de meta
0,alejandro arbelaez ramirez,1,Número de proyectos de inversión de la región ...
1,eduardo andres sanchez,3,Número de proyectos de inversión de la región ...
2,juan esteban vasquez montoya,1,Número de proyectos de inversión de la región ...
3,katherine caicedo tapasco,1,Número de proyectos de inversión de la región ...

In [142]:
Regional = Regional.merge(pp, how='left', left_on=['Meta: Tipo de meta' , 'Meta: Nombre del propietario'], right_on=['Meta: Tipo de meta' , 'Meta: Nombre del propietario']).fillna(0)
Regional['Resultado'] = Regional['Resultado'] + Regional['Portafolio de oportunidades: Consecutivo'] 
Regional = Regional.drop(columns=['Portafolio de oportunidades: Consecutivo'])

### Cuentas con Servicios

In [143]:
#ServiciosCovid

## HUB

In [144]:
MetasH = Metas.drop(Metas[Metas['Meta: Eje'] != 'Inversión'].index)

MetasH = MetasH.drop(MetasH[MetasH['Meta: Año'] !=  añoactual].index)

MetasH = MetasH.drop(MetasH[MetasH['Meta: Tipo meta funcionario'] != 'EXTERIOR'].index)



MetasQH = MetasH.drop(MetasH[MetasH['Meta: Período'] > trimestre].index)

In [145]:
aH = MetasH.groupby(['E_Localización' ,'Meta: Nombre del propietario' ,'Meta: Tipo de meta' ])['Meta: Valor meta'].sum().reset_index()
a2H = MetasQH.groupby(['E_Localización' ,'Meta: Nombre del propietario' ,'Meta: Tipo de meta'])['Meta: Valor meta'].sum().reset_index()

MetasdfH = aH.merge(a2H, how='outer', left_on=['E_Localización' ,  'Meta: Tipo de meta' , 'Meta: Nombre del propietario'], right_on=['E_Localización' , 'Meta: Tipo de meta' , 'Meta: Nombre del propietario']).fillna(0)
MetasdfH.rename(columns={'Meta: Valor meta_x': 'Valor Meta', 'Meta: Valor meta_y': 'Valor Meta Q'}, inplace=True)

In [146]:
NegociosH = Negocios.drop(Negocios[Negocios['Logro: Eje'] != 'Inversión'].index)
NegociosH = NegociosH.drop(NegociosH[NegociosH['Meta 1 responsable Colombia: Año'] !=  añoactual].index)
NegociosH = NegociosH.drop(NegociosH[NegociosH['Logro: Tipo de registro'] !=  'Monto de Inversión'].index)

In [147]:
MIH = NegociosH.groupby(['Logro: Oficina Comercial', 'Logro: Responsable en el Exterior 1' ,'Logro: Tipo de registro' ])['Logro: Valor'].sum().reset_index()
MIH.rename(columns={'Logro: Oficina Comercial': 'E_Localización' , 'Logro: Responsable en el Exterior 1':'Meta: Nombre del propietario' , 'Logro: Tipo de registro':'Meta: Tipo de meta'  }, inplace=True)
HUB = MetasdfH.merge(MIH, how='left', left_on=['E_Localización' ,  'Meta: Tipo de meta' ,'Meta: Nombre del propietario'], 
                     right_on=['E_Localización' , 'Meta: Tipo de meta' , 'Meta: Nombre del propietario']).fillna(0)

HUB.rename(columns={'Logro: Valor': 'Resultados'  }, inplace=True)

In [148]:
HUB

,E_Localización,Meta: Nombre del propietario,Meta: Tipo de meta,Valor Meta,Valor Meta Q,Resultados
0,alemania,carlos alvarez awakon (vacante),Monto de Inversión,480000000.0,240000000.0,76000000.0
1,alemania,carlos alvarez awakon (vacante),Número de oportunidades de Inversión a etapa 1,13.0,4.0,0.0
2,alemania,carlos alvarez awakon (vacante),Número de oportunidades de Inversión a etapa 2,10.0,3.0,0.0
3,alemania,carlos alvarez awakon (vacante),Número de oportunidades de Inversión a etapa 3,6.0,2.0,0.0
4,alemania,carlos alvarez awakon (vacante),Proyectos Inversión,8.0,4.0,0.0
...,...,...,...,...,...,...
178,émiratos árabes unidos,tatiana andrea cordoba arteaga,Monto de Inversión,150000000.0,75000000.0,0.0
179,émiratos árabes unidos,tatiana andrea cordoba arteaga,Número de oportunidades de Inversión a etapa 1,21.0,6.0,0.0
180,émiratos árabes unidos,tatiana andrea cordoba arteaga,Número de oportunidades de Inversión a etapa 2,8.0,3.0,0.0
181,émiratos árabes unidos,tatiana andrea cordoba arteaga,Número de oportunidades de Inversión a etapa 3,4.0,1.0,0.0
182,émiratos árabes unidos,tatiana andrea cordoba arteaga,Proyectos Inversión,2.0,1.0,0.0

## Proyectos

In [149]:
py2 = Negocios1.groupby([ 'Logro: Oficina Comercial', 'Logro: Responsable en el Exterior 1' ])['E_ConteoProyectosInversión'].sum().reset_index()
py2['Meta: Tipo de meta']= 'Proyectos Inversión'
py2.rename(columns={'Logro: Oficina Comercial':'E_Localización', 'Logro: Responsable en el Exterior 1': 'Meta: Nombre del propietario'}, inplace=True)

HUB = HUB.merge(py2, how='left', left_on=['E_Localización' , 'Meta: Nombre del propietario' , 'Meta: Tipo de meta'],
                      right_on=['E_Localización' ,'Meta: Nombre del propietario' , 'Meta: Tipo de meta']).fillna(0)
HUB['Resultados'] = HUB['Resultados'] + HUB['E_ConteoProyectosInversión']
HUB = HUB.drop(columns=['E_ConteoProyectosInversión'])

In [150]:
writer = pd.ExcelWriter('TCV-Inversion.xlsx')
TFinal.to_excel(writer, 'Gerencias')
Regional.to_excel(writer , 'Regional')
HUB.to_excel(writer , 'HUB')
writer.save()
from IPython.display import FileLink
FileLink('TCV-Inversion.xlsx')

E:\Usuario\pplaneacion\Documents\Códigos Python\TCV-Inversion.xlsx